window.LAW_DATA = [
  // Psychische & Physische Integrität (StGB)
  { id: "stgb-3-1", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §3.1", name: "Beleidigung", fineType: "fixed", fine: 10000, fixedWanted: 0, grayWantedMax: 1 },
  { id: "stgb-3-2", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §3.2", name: "Belästigung", fineType: "fixed", fine: 10000, fixedWanted: 0, grayWantedMax: 1 },
  { id: "stgb-3-3", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §3.3", name: "Drohung", fineType: "fixed", fine: 5000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stgb-4-1", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §4.1", name: "Versuchter Mord / Mord", fineType: "fixed", fine: 30000, fixedWanted: 4, grayWantedMax: 0 },
  { id: "stgb-4-2", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §4.2", name: "Körperverletzung", fineType: "fixed", fine: 15000, fixedWanted: 2, grayWantedMax: 0 },
  { id: "stgb-4-3", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §4.3", name: "Körperverletzung mit Todesfolge", fineType: "fixed", fine: 20000, fixedWanted: 3, grayWantedMax: 0 },
  { id: "stgb-4-4", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §4.4", name: "Gewaltsame Drohung", fineType: "per_active_wanted", finePerWanted: 5000, fixedWanted: 1, grayWantedMax: 1, infoList: ["5.000$ pro ★"] },
  { id: "stgb-4-5", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §4.5", name: "Fahrlässige Tötung", fineType: "fixed", fine: 20000, fixedWanted: 3, grayWantedMax: 0 },
  { id: "stgb-5", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §5", name: "Sexuelle Belästigung", fineType: "base_plus_per_active_wanted", fine: 30000, finePerWanted: 10000, fixedWanted: 1, grayWantedMax: 2, infoList: ["30.000$ + 10.000$ pro ★"] },
  { id: "stgb-20", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §20", name: "Sachbeschädigung", fineType: "base_plus_per_active_wanted", fine: 5000, finePerWanted: 5000, fixedWanted: 0, grayWantedMax: 2, infoList: ["5.000$ + 5.000$ pro weiterem ★"] },
  { id: "stgb-21", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §21", name: "Unterlassene Hilfeleistung", fineType: "fixed", fine: 5000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stgb-26", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §26", name: "Prostitution", fineType: "fixed", fine: 10000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stgb-27", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §27", name: "Freiheitsberaubung / Geiselnahmen / Entführung", fineType: "fixed", fine: 30000, fixedWanted: 3, grayWantedMax: 0 },
  { id: "stgb-28", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §28", name: "Errichtung von Straßenbarrikaden", fineType: "base_plus_per_active_wanted", fine: 10000, finePerWanted: 10000, fixedWanted: 0, grayWantedMax: 2, infoList: ["10.000$ + 10.000$ pro weiterem ★"] },
  { id: "stgb-31", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §31", name: "Verhalten in der Öffentlichkeit", fineType: "fixed", fine: 5000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stgb-32", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §32", name: "Rassismus / Nachstellung (Stalking)", fineType: "fixed", fine: 15000, fixedWanted: 3, grayWantedMax: 0 },
  { id: "stgb-38", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §38", name: "Fischwilderei", fineType: "fixed", fine: 5000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stgb-39", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §39", name: "Verleumdung", fineType: "fixed", fine: 30000, fixedWanted: 0, grayWantedMax: 3 },
  { id: "stgb-42", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §42", name: "Erpressung", fineType: "fixed", fine: 45000, fixedWanted: 3, grayWantedMax: 0 },
  { id: "stgb-43", group: "Psychische & Physische Integrität (StGB)", section: "STGB", para: "StGB §43", name: "Androhung einer Straftat", fineType: "base_plus_per_active_wanted", fine: 20000, finePerWanted: 5000, fixedWanted: 0, grayWantedMax: 3, infoList: ["20.000$ + 5.000$ pro ★"] },

  // Wirtschaftskriminalität (StGB)
  { id: "stgb-6-9", group: "Wirtschaftskriminalität (StGB)", section: "STGB", para: "StGB §6 / §9", name: "Diebstahl / Betrug", fineType: "base_plus_per_active_wanted", fine: 5000, finePerWanted: 5000, fixedWanted: 0, grayWantedMax: 3, infoList: ["5.000$ + 5.000$ pro weiterem ★"] },
  { id: "stgb-7", group: "Wirtschaftskriminalität (StGB)", section: "STGB", para: "StGB §7", name: "Fahrzeug Diebstahl", fineType: "fixed", fine: 10000, fixedWanted: 2, grayWantedMax: 0 },
  { id: "stgb-10-1", group: "Wirtschaftskriminalität (StGB)", section: "STGB", para: "StGB §10.1", name: "Besitz illegaler Gegenstände", fineType: "fixed", fine: 10000, fixedWanted: 2, grayWantedMax: 0 },
  { id: "stgb-11", group: "Wirtschaftskriminalität (StGB)", section: "STGB", para: "StGB §11", name: "Raub", fineType: "fixed", fine: 25000, fixedWanted: 3, grayWantedMax: 0 },
  { id: "stgb-12-1", group: "Wirtschaftskriminalität (StGB)", section: "STGB", para: "StGB §12.1", name: "Geschäfts Raub / Ammu Rob", fineType: "fixed", fine: 35000, fixedWanted: 2, grayWantedMax: 0 },
  { id: "stgb-12-3", group: "Wirtschaftskriminalität (StGB)", section: "STGB", para: "StGB §12.3", name: "ATM Raub", fineType: "fixed", fine: 5000, fixedWanted: 1, grayWantedMax: 0 },
  { id: "stgb-13", group: "Wirtschaftskriminalität (StGB)", section: "STGB", para: "StGB §13", name: "Einbruch", fineType: "fixed", fine: 15000, fixedWanted: 2, grayWantedMax: 0 },
  { id: "stgb-14", group: "Wirtschaftskriminalität (StGB)", section: "STGB", para: "StGB §14", name: "Steuerhinterziehung", fineType: "fixed", fine: 60000, fixedWanted: 3, grayWantedMax: 0 },
  { id: "stgb-30", group: "Wirtschaftskriminalität (StGB)", section: "STGB", para: "StGB §30", name: "Hausfriedensbruch", fineType: "fixed", fine: 25000, fixedWanted: 3, grayWantedMax: 0 },
  { id: "stgb-41-1", group: "Wirtschaftskriminalität (StGB)", section: "STGB", para: "StGB §41.1", name: "Besitz staatliches Eigentum (Waffen)", fineType: "fixed", fine: 50000, fixedWanted: 3, grayWantedMax: 0, infoList: ["Waffenscheinentzug"] },
  { id: "stgb-41-2", group: "Wirtschaftskriminalität (StGB)", section: "STGB", para: "StGB §41.2", name: "Besitz staatliches Eigentum (Gegenstände)", fineType: "fixed", fine: 50000, fixedWanted: 3, grayWantedMax: 0 },

  // Umgang mit Beamten (StGB)
  { id: "stgb-15-1", group: "Umgang mit Beamten (StGB)", section: "STGB", para: "StGB §15.1", name: "Nichtbeachten einer amtlichen Anweisung", fineType: "fixed", fine: 10000, fixedWanted: 0, grayWantedMax: 2 },
  { id: "stgb-15-2", group: "Umgang mit Beamten (StGB)", section: "STGB", para: "StGB §15.2", name: "Entziehung polizeilicher Maßnahmen", fineType: "fixed", fine: 10000, fixedWanted: 2, grayWantedMax: 0 },
  { id: "stgb-15-3", group: "Umgang mit Beamten (StGB)", section: "STGB", para: "StGB §15.3", name: "Behinderung eines Beamten bei der Arbeit", fineType: "fixed", fine: 10000, fixedWanted: 1, grayWantedMax: 0 },
  { id: "stgb-15-6", group: "Umgang mit Beamten (StGB)", section: "STGB", para: "StGB §15.6", name: "Behinderung des EMS bei der Arbeit", fineType: "fixed", fine: 10000, fixedWanted: 0, grayWantedMax: 2 },
  { id: "stgb-15-4", group: "Umgang mit Beamten (StGB)", section: "STGB", para: "StGB §15.4", name: "Bestechung von Beamten", fineType: "fixed", fine: 10000, fixedWanted: 2, grayWantedMax: 0 },
  { id: "stgb-15-5", group: "Umgang mit Beamten (StGB)", section: "STGB", para: "StGB §15.5", name: "Widerstand gegen Vollstreckungsbeamte", fineType: "fixed", fine: 20000, fixedWanted: 2, grayWantedMax: 0 },
  { id: "stgb-15-7", group: "Umgang mit Beamten (StGB)", section: "STGB", para: "StGB §15.7", name: "Nicht ausweisen bei einer polizeilichen / medizinischen Maßnahme", fineType: "fixed", fine: 15000, fixedWanted: 1, grayWantedMax: 0, infoList: ["Führerscheinentzug"] },
  { id: "stgb-16", group: "Umgang mit Beamten (StGB)", section: "STGB", para: "StGB §16", name: "Befreiung von Gefangenen", fineType: "per_active_wanted", finePerWanted: 10000, fixedWanted: 1, grayWantedMax: 3, infoList: ["10.000$ pro ★"] },
  { id: "stgb-19", group: "Umgang mit Beamten (StGB)", section: "STGB", para: "StGB §19", name: "Falsche Namensangabe", fineType: "fixed", fine: 10000, fixedWanted: 0, grayWantedMax: 1 },
  { id: "stgb-23", group: "Umgang mit Beamten (StGB)", section: "STGB", para: "StGB §23", name: "Missbrauch von Notruf", fineType: "fixed", fine: 30000, fixedWanted: 0, grayWantedMax: 2 },
  { id: "stgb-24", group: "Umgang mit Beamten (StGB)", section: "STGB", para: "StGB §24", name: "Amtsanmaßung", fineType: "fixed", fine: 25000, fixedWanted: 2, grayWantedMax: 1 },
  { id: "stgb-29", group: "Umgang mit Beamten (StGB)", section: "STGB", para: "StGB §29", name: "Missachtung eines Platzverweises", fineType: "fixed", fine: 20000, fixedWanted: 1, grayWantedMax: 1 },

  // Straßenverkehrsordnung (StVO)
  { id: "stvo-2", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §2", name: "Gefährdung anderer Verkehrsteilnehmer", fineType: "fixed", fine: 10000, fixedWanted: 0, grayWantedMax: 0, infoList: ["Führerscheinentzug"] },
  { id: "stvo-4", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §4", name: "Missachten von Rechtsfahrgebot", fineType: "fixed", fine: 3000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-5", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §5", name: "Überschreiten der Fahrzeugkapazitäten", fineType: "fixed", fine: 5000, fixedWanted: 0, grayWantedMax: 0, infoList: ["Führerscheinentzug"] },
  { id: "stvo-6", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §6", name: "Fahren mit demoliertem Fahrzeug", fineType: "fixed", fine: 2000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-7", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §7", name: "Fahren ohne Licht (Dunkelheit, Wetterverhältnissen)", fineType: "fixed", fine: 5000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-8-10-40", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §8", name: "Geschwindigkeitsüberschreitung 10 - 40 km/h", fineType: "fixed", fine: 5000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-8-41-60", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §8", name: "Geschwindigkeitsüberschreitung 41 - 60 km/h", fineType: "fixed", fine: 10000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-8-61-100", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §8", name: "Geschwindigkeitsüberschreitung 61 - 100 km/h", fineType: "fixed", fine: 15000, fixedWanted: 0, grayWantedMax: 0, infoList: ["Führerscheinentzug"] },
  { id: "stvo-8-101plus", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §8", name: "Geschwindigkeitsüberschreitung ab 101 km/h", fineType: "fixed", fine: 20000, fixedWanted: 0, grayWantedMax: 0, infoList: ["Führerscheinentzug"] },
  { id: "stvo-9-art-3", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §9 Art. 3", name: "Fahren ohne gültige Zulassung", fineType: "fixed", fine: 10000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-10-art-1", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §10 Art. 1", name: "Missachten von Rechts vor Links", fineType: "fixed", fine: 1000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-10-art-2", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §10 Art. 2", name: "Missachten von Verkehrsschildern", fineType: "fixed", fine: 2000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-10-art-4", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §10 Art. 4", name: "Fahren ohne genügend Tankkapazität", fineType: "fixed", fine: 10000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-10-art-6", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §10 Art. 6", name: "Nutzung eines Mobilgeräts am Steuer", fineType: "fixed", fine: 3000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-10-art-7", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §10 Art. 7", name: "Lärmbelästigung / Unnötiges Hupen", fineType: "fixed", fine: 20000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-10-art-9-1", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §10 Art. 9(1)", name: "Überholen auf der rechten Fahrbahn", fineType: "fixed", fine: 5000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-10-art-12", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §10 Art. 12", name: "Fahren abseits von gekennzeichneten Wegen", fineType: "fixed", fine: 8000, fixedWanted: 0, grayWantedMax: 0, infoList: ["Führerscheinentzug"] },
  { id: "stvo-10-art-16", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §10 Art. 16", name: "Fahren auf der entgegengesetzten Fahrtrichtung", fineType: "fixed", fine: 30000, fixedWanted: 0, grayWantedMax: 0, infoList: ["Führerscheinentzug"] },
  { id: "stvo-12-1", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §12.1", name: "Falsch Parken / Halten", fineType: "fixed", fine: 10000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-12-3", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §12.3", name: "Bergung aus nicht befahrbarem Gelände", fineType: "fixed", fine: 20000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-17-art-1-2", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §17 Art. 1+2", name: "Fahren im berauschten Zustand", fineType: "fixed", fine: 10000, fixedWanted: 0, grayWantedMax: 2, infoList: ["Führerscheinentzug"] },
  { id: "stvo-19", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §19", name: "Fahren ohne Erste-Hilfe-Kit (Kofferraum)", fineType: "fixed", fine: 5000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-20", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §20", name: "Fahren ohne Gurt (nicht angeschnallt)", fineType: "fixed", fine: 5000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-24", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §24", name: "Fahrerflucht", fineType: "fixed", fine: 10000, fixedWanted: 1, grayWantedMax: 0, infoList: ["Führerscheinentzug"] },
  { id: "stvo-26", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §26", name: "Abschleppkosten", fineType: "fixed", fine: 15000, fixedWanted: 0, grayWantedMax: 0, infoList: ["15.000$ / 20.000$ je nach Fall"] },
  { id: "stvo-27", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §27", name: "Fahren ohne KFZ Versicherung", fineType: "fixed", fine: 20000, fixedWanted: 0, grayWantedMax: 0 },
  { id: "stvo-28", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §28", name: "Sharing-Cars mit Anti-Radar wurde nicht aus dem Verkehr gezogen", fineType: "fixed", fine: 30000, fixedWanted: 3, grayWantedMax: 0, infoList: ["Führerscheinentzug"] },
  { id: "stvo-10-art-8", group: "Straßenverkehrsordnung (StVO)", section: "STVO", para: "StVO §10 Art. 8", name: "Helmpflicht", fineType: "fixed", fine: 10000, fixedWanted: 0, grayWantedMax: 0 },

  // Waffengesetz (WaffG)
  { id: "waffg-1", group: "Waffengesetz (WaffG)", section: "WAFFG", para: "WaffG §1", name: "Besitz legaler Waffen ohne Waffenschein", fineType: "per_active_wanted", finePerWanted: 10000, fixedWanted: 1, grayWantedMax: 1, infoList: ["10.000$ pro ★"] },
  { id: "waffg-5-1", group: "Waffengesetz (WaffG)", section: "WAFFG", para: "WaffG §5.1", name: "Besitz illegaler Waffen", fineType: "per_active_wanted", finePerWanted: 10000, fixedWanted: 2, grayWantedMax: 1, infoList: ["10.000$ pro ★", "Waffenscheinentzug"] },
  { id: "waffg-8-1", group: "Waffengesetz (WaffG)", section: "WAFFG", para: "WaffG §8.1", name: "Offenes Tragen einer Waffe", fineType: "fixed", fine: 5000, fixedWanted: 0, grayWantedMax: 1, infoList: ["Waffenscheinentzug"] },
  { id: "waffg-8-2", group: "Waffengesetz (WaffG)", section: "WAFFG", para: "WaffG §8.2", name: "Tragen einer Waffe in staatl. Einrichtungen", fineType: "fixed", fine: 5000, fixedWanted: 0, grayWantedMax: 1, infoList: ["Waffenscheinentzug"] },
  { id: "waffg-11", group: "Waffengesetz (WaffG)", section: "WAFFG", para: "WaffG §11", name: "Ungesetzlicher Waffenhandel (An- & Verkauf)", fineType: "fixed", fine: 25000, fixedWanted: 3, grayWantedMax: 0, infoList: ["Waffenscheinentzug"] },

  // Sperrzonen / Absperrungen / Kapitalverbrechen (StGB)
  { id: "stgb-17-sperr", group: "Sperrzonen / Absperrungen / Kapitalverbrechen (StGB)", section: "STGB", para: "StGB §17", name: "Durchbrechen von Absperrungen", fineType: "fixed", fine: 15000, fixedWanted: 1, grayWantedMax: 1 },
  { id: "stgb-18", group: "Sperrzonen / Absperrungen / Kapitalverbrechen (StGB)", section: "STGB", para: "StGB §18", name: "Unerlaubtes Betreten eines militärischen Geländes", fineType: "fixed", fine: 50000, fixedWanted: 5, grayWantedMax: 0 },
  { id: "stgb-18-1", group: "Sperrzonen / Absperrungen / Kapitalverbrechen (StGB)", section: "STGB", para: "StGB §18.1", name: "Unerlaubtes Betreten von Sperrzonen", fineType: "fixed", fine: 25000, fixedWanted: 3, grayWantedMax: 0 },
  { id: "stgb-18-2", group: "Sperrzonen / Absperrungen / Kapitalverbrechen (StGB)", section: "STGB", para: "StGB §18.2", name: "Unerlaubtes Befahren von Sperrzonen", fineType: "fixed", fine: 25000, fixedWanted: 2, grayWantedMax: 1, infoList: ["Führerscheinentzug"] },
  { id: "stgb-25", group: "Sperrzonen / Absperrungen / Kapitalverbrechen (StGB)", section: "STGB", para: "StGB §25", name: "Terrorismus (deckt alle Strafen ab)", fineType: "fixed", fine: 25000, fixedWanted: 3, grayWantedMax: 0 },

  // Betäubungsmittelgesetz (BtMG)
  { id: "btmg-2-1-kokain-klein", group: "Betäubungsmittelgesetz (BtMG)", section: "BTMG", para: "BtMG §2.1", name: "Kokainbesitz Klein ab 11 - 30", fineType: "fixed", fine: 15000, fixedWanted: 0, grayWantedMax: 1 },
  { id: "btmg-2-1-weed-klein", group: "Betäubungsmittelgesetz (BtMG)", section: "BTMG", para: "BtMG §2.1", name: "Marihuana Besitz Klein 21 - 30", fineType: "fixed", fine: 15000, fixedWanted: 0, grayWantedMax: 1 },
  { id: "btmg-2-1-mittel", group: "Betäubungsmittelgesetz (BtMG)", section: "BTMG", para: "BtMG §2.1", name: "Drogenbesitz Mittel ab 31 - 50", fineType: "fixed", fine: 20000, fixedWanted: 1, grayWantedMax: 0 },
  { id: "btmg-2-1-gross", group: "Betäubungsmittelgesetz (BtMG)", section: "BTMG", para: "BtMG §2.1", name: "Drogenbesitz Groß 50+", fineType: "fixed", fine: 30000, fixedWanted: 2, grayWantedMax: 0 },
  { id: "btmg-2-2", group: "Betäubungsmittelgesetz (BtMG)", section: "BTMG", para: "BtMG §2.2", name: "Drogenhandel (An- & Verkauf)", fineType: "fixed", fine: 30000, fixedWanted: 3, grayWantedMax: 0, infoList: ["Erst ab 20g Marihuana"] },
  { id: "btmg-2-1-herstellung", group: "Betäubungsmittelgesetz (BtMG)", section: "BTMG", para: "BtMG §2.1", name: "Drogen Herstellung", fineType: "fixed", fine: 30000, fixedWanted: 3, grayWantedMax: 0 },
  { id: "btmg-3-bis-20", group: "Betäubungsmittelgesetz (BtMG)", section: "BTMG", para: "BtMG §3", name: "Verkauf von Medizinprodukten bis 20 medizinischen Gegenständen", fineType: "fixed", fine: 10000, fixedWanted: 1, grayWantedMax: 0, infoList: ["+ zusätzlich die verlangte Verkaufssumme"] },
  { id: "btmg-3-bis-50", group: "Betäubungsmittelgesetz (BtMG)", section: "BTMG", para: "BtMG §3", name: "Verkauf von Medizinprodukten bis 50 medizinischen Gegenständen", fineType: "fixed", fine: 20000, fixedWanted: 1, grayWantedMax: 1, infoList: ["+ zusätzlich die verlangte Verkaufssumme"] },
  { id: "btmg-3-ab-51", group: "Betäubungsmittelgesetz (BtMG)", section: "BTMG", para: "BtMG §3", name: "Verkauf von Medizinprodukten ab 51 medizinischen Gegenständen", fineType: "fixed", fine: 25000, fixedWanted: 1, grayWantedMax: 2, infoList: ["+ zusätzlich die verlangte Verkaufssumme"] },

  // Strafprozessordnung (StPO)
  { id: "stpo-6", group: "Strafprozessordnung (StPO)", section: "STPO", para: "§8 StPO", name: "Bußgelder nicht bezahlt (500k voll)", fineType: "fixed", fine: 500000, fixedWanted: 5, grayWantedMax: 0 },

  // Beamtendienstgesetzbuch (BDG)
  { id: "bdg-2", group: "Beamtendienstgesetzbuch (BDG)", section: "BDG", para: "BDG §2", name: "Verhaltenskodex", fineType: "fixed", fine: 50000, fixedWanted: 0, grayWantedMax: 5, note: "max. 50.000$" },
  { id: "bdg-3", group: "Beamtendienstgesetzbuch (BDG)", section: "BDG", para: "BDG §3", name: "Dienstpflichten des Beamten", fineType: "fixed", fine: 50000, fixedWanted: 0, grayWantedMax: 5, note: "max. 50.000$" },
  { id: "bdg-7", group: "Beamtendienstgesetzbuch (BDG)", section: "BDG", para: "BDG §7", name: "Bestechlichkeit", fineType: "fixed", fine: 50000, fixedWanted: 0, grayWantedMax: 5, note: "max. 50.000$" },
  { id: "bdg-8", group: "Beamtendienstgesetzbuch (BDG)", section: "BDG", para: "BDG §8", name: "Vorteilsannahme & Vorteilsgewährung", fineType: "fixed", fine: 50000, fixedWanted: 0, grayWantedMax: 5, note: "max. 50.000$" },
  { id: "bdg-9", group: "Beamtendienstgesetzbuch (BDG)", section: "BDG", para: "BDG §9", name: "Verleitung eines Untergebenen/Kollegen zur Straftat", fineType: "fixed", fine: 50000, fixedWanted: 0, grayWantedMax: 5, note: "max. 50.000$" },
  { id: "bdg-10", group: "Beamtendienstgesetzbuch (BDG)", section: "BDG", para: "BDG §10", name: "Unterlassen der Diensthandlung", fineType: "fixed", fine: 50000, fixedWanted: 0, grayWantedMax: 5, note: "max. 50.000$" },
  { id: "bdg-11", group: "Beamtendienstgesetzbuch (BDG)", section: "BDG", para: "BDG §11", name: "Falschbeurkundung im Amt", fineType: "fixed", fine: 50000, fixedWanted: 0, grayWantedMax: 5, note: "max. 50.000$" },
  { id: "stgb-40", group: "Beamtendienstgesetzbuch (BDG)", section: "BDG", para: "StGB §40", name: "Weitergabe von Staatseigentum", fineType: "fixed", fine: 50000, fixedWanted: 0, grayWantedMax: 5, note: "max. 50.000$" },
  { id: "bdg-13", group: "Beamtendienstgesetzbuch (BDG)", section: "BDG", para: "BDG §13", name: "Hochverrat im öffentlichen Dienst", fineType: "fixed", fine: 50000, fixedWanted: 0, grayWantedMax: 5, note: "max. 50.000$" },
  { id: "bdg-14", group: "Beamtendienstgesetzbuch (BDG)", section: "BDG", para: "BDG §14", name: "Umgehung von Strafprozessen", fineType: "fixed", fine: 50000, fixedWanted: 0, grayWantedMax: 5, note: "max. 50.000$" },
  { id: "bdg-15", group: "Beamtendienstgesetzbuch (BDG)", section: "BDG", para: "BDG §15", name: "Verschwörung", fineType: "fixed", fine: 50000, fixedWanted: 0, grayWantedMax: 5, note: "max. 50.000$" },
  { id: "bdg-16", group: "Beamtendienstgesetzbuch (BDG)", section: "BDG", para: "BDG §16", name: "Schmuggel", fineType: "fixed", fine: 50000, fixedWanted: 0, grayWantedMax: 5, note: "max. 50.000$" }
];

window.GROUP_ORDER = [
  "Psychische & Physische Integrität (StGB)",
  "Wirtschaftskriminalität (StGB)",
  "Umgang mit Beamten (StGB)",
  "Straßenverkehrsordnung (StVO)",
  "Waffengesetz (WaffG)",
  "Sperrzonen / Absperrungen / Kapitalverbrechen (StGB)",
  "Betäubungsmittelgesetz (BtMG)",
  "Strafprozessordnung (StPO)",
  "Beamtendienstgesetzbuch (BDG)"
];

window.FIBCO_FIELD_IDS = [
  "fibcoName",
  "fibcoCoId",
  "fibcoDate",
  "fibcoCodename",
  "fibcoPhone",
  "fibcoAgency",
  "fibcoFamily",
  "fibcoPassport",
  "fibcoBadge",
  "fibcoPersonnel",
  "fibcoPdaMain",
  "fibcoPdaVehicles",
  "fibcoIncident",
  "fibcoInterrogation",
  "fibcoWitness",
  "fibcoEvidence",
  "fibcoConclusion"
];
